---
volumes:
  netdataconfig: {}
  netdatalib: {}
  netdatacache: {}

networks:
  caddy:
    external: true

services:
  netdata:
    image: netdata/netdata:${NETDATA_VERSION}
    restart: unless-stopped
    container_name: ${HOSTNAME}
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    networks:
      - default
      - caddy
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro
    labels:
      caddy: netdata.mafro.net
      caddy.tls.ca: https://ca.mafro.net:4433/acme/acme/directory
      caddy.tls.ca_root: /root/step_ca.crt
      caddy.reverse_proxy: "{{upstreams 19999}}"
